include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

variables:
  L5_DOCKER_IMAGE: "debian:bullseye"
  L5_ADD_SCRATCH_CI: "false"

stages:
 - package
 - test-package

package:deb-debian-bullseye:
  extends: .l5-build-debian-package

package:deb-debian-bullseye:arm64:
  tags:
    - librem5:arm64
  extends: .l5-build-debian-package

lintian-debian-bullseye-package:
  dependencies:
    - package:deb-debian-bullseye
  extends: .l5-lintian-debian-package

check-tarball:
  extends: .l5-check-tarball
  only:
    changes:
      - "debian/changelog"
